# Generated by Django 4.2.3 on 2023-07-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uaser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uaser',
            new_name='User',
        ),
    ]
